title: Srinivas Kolluru  # You can add your name here

logo: IMG_6206.JPG # Use a relative path to logo image 

description: Remote sensing and Marine optics. # Fix hyphenation 

show_downloads: true # Fix spelling

theme: jekyll-theme-minimal 

plugins:
  - jekyll-seo-tag # Add SEO plugin

email: srinivaskolluru.a1@gmail.com # Allow visitors to contact you

